from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

SAFE = "SAFE"
CAUTION = "CAUTION"
FORBIDDEN = "FORBIDDEN"

TIER_RANK = {SAFE: 0, CAUTION: 1, FORBIDDEN: 2}

LANDMARK_DIRS = {
    "node_modules", ".venv", "venv", "target", "DerivedData", ".next",
    ".nuxt", ".turbo", ".svelte-kit", "__pycache__", ".pytest_cache",
    ".mypy_cache", ".gradle", "Pods", "site-packages", ".git",
}

SAFE_REGEN = {
    "node_modules": "npm install (or pnpm/yarn install) in the project",
    "__pycache__": "regenerated on next Python run",
    ".pytest_cache": "regenerated on next pytest run",
    ".mypy_cache": "regenerated on next mypy run",
    ".next": "regenerated on next next build/dev",
    ".nuxt": "regenerated on next nuxt build/dev",
    ".turbo": "regenerated on next turbo run",
    ".svelte-kit": "regenerated on next vite dev/build",
    ".gradle": "regenerated on next gradle build",
    "Pods": "pod install in the project",
    "DerivedData": "rebuilt on next Xcode compile",
    "target": "regenerated by cargo/maven/gradle build",
}


@dataclass
class Hit:
    tier: str
    rule_key: str
    regen: str = ""
    note: str = ""


def _parts(path: str) -> list[str]:
    return [p for p in path.split("/") if p]


def _home_top(path: str, home: str) -> str | None:
    rel = path[len(home):].lstrip("/")
    return rel.split("/")[0] if rel else None


def classify_path(path: str, name: str, is_dir: bool, home: str) -> Hit | None:
    top = _home_top(path, home)

    if top in {"Documents", "Pictures", "Movies", "Music", "Desktop", "Public"}:
        return Hit(FORBIDDEN, "user-data", note="personal user data, never proposed")
    if top == ".ssh" or "/.ssh/" in path:
        return Hit(FORBIDDEN, "credentials", note="credentials and keys")
    if top == "Library" and "/Keychains" in path:
        return Hit(FORBIDDEN, "credentials", note="system keychain")
    if name == ".git" or "/.git/" in path or path.endswith("/.git"):
        return Hit(FORBIDDEN, "git", note="manage via git, not deletion")
    if not is_dir and (name.startswith(".env") or name.endswith((".pem", ".p12", ".key"))):
        return Hit(FORBIDDEN, "credentials", note="secret material")
    if name in {"Docker.raw", "Docker.qcow2"}:
        return Hit(FORBIDDEN, "docker-vm",
                   note="deleting destroys all images without prune; use docker system prune")
    if top == "Library" and "/Xcode/Archives" in path:
        return Hit(FORBIDDEN, "xcode-archives", note="distribution archives and dSYMs, irreplaceable")

    if not is_dir and Path(path).parent.name == "Downloads" and name.endswith((".dmg", ".pkg", ".iso", ".tgz")):
        return Hit(SAFE, "downloads-installers", regen="re-download from vendor",
                   note="installer already applied or re-obtainable")

    if name in SAFE_REGEN:
        return Hit(SAFE, name, regen=SAFE_REGEN[name], note="regenerable build artifact")

    if path.endswith("/.npm") or "/.npm/_cacache" in path:
        return Hit(SAFE, "npm-cache", regen="npm cache clean --force; redownloaded on install")
    if "/.cache/pip" in path or "/Caches/pip" in path:
        return Hit(SAFE, "pip-cache", regen="pip cache purge; redownloaded on install")
    if "/Caches/Homebrew" in path or path.endswith("/.cache/Homebrew"):
        return Hit(SAFE, "brew-cache", regen="brew cleanup; redownloaded on install")
    if "/.cargo/registry" in path:
        return Hit(SAFE, "cargo-cache", regen="redownloaded on next cargo build")
    if "/Caches/go-build" in path or path.endswith("/.cache/go-build"):
        return Hit(SAFE, "go-build-cache", regen="go clean -cache; rebuilt on demand")
    if "/.yarn/cache" in path or "/pnpm/store" in path:
        return Hit(SAFE, "pkg-store", regen="redownloaded on next install")

    if name in {"venv", ".venv"}:
        return Hit(CAUTION, "venv",
                   regen="recreate from requirements.txt/pyproject.toml if present",
                   note="check parent project is not actively using it")
    if "/Caches/JetBrains" in path:
        return Hit(CAUTION, "jetbrains-cache", regen="indexes rebuild on next IDE open (slow)")
    if "/Caches/com.spotify.client" in path:
        return Hit(CAUTION, "spotify-cache", regen="music re-streamed; offline downloads lost",
                   note="may hold offline library despite cache location")
    if "/CoreSimulator/Devices" in path:
        return Hit(CAUTION, "simulator-devices", regen="device states lost; recreatable")
    if name in {"build", "dist", "out"}:
        return Hit(CAUTION, "build-output", regen="rebuilt by build tool; may be a deployable artifact")

    if "/Library/Caches/" in path and is_dir:
        return Hit(CAUTION, "app-cache", note="app cache; may hold state despite cache location")
    if "/Library/Application Support/" in path and is_dir:
        return Hit(CAUTION, "app-support", note="application state, may include user data")
    if "/Library/Containers/" in path and is_dir:
        return Hit(CAUTION, "app-container", note="sandboxed app data container")

    return None


PROCESS_HINTS = {
    "spotify-cache": "Spotify",
    "jetbrains-cache": None,
    "docker-vm": "Docker",
}


def process_name_for(rule_key: str) -> str | None:
    return PROCESS_HINTS.get(rule_key)
